### ISSUE TITLE
Help with the usage beyond the very simple example

### ISSUE THREAD

**Issue by celavek** [HadrienG2/triple-buffer#17]
I'm trying to use the triple_buffer crate as in
https://docs.rs/triple_buffer/latest/triple_buffer/

I have the following:

```rust
struct MyOtherStruct {
    ...
}
impl MyOtherStruct {
    ...
}
```

```rust
struct MyStruct {
    buffer: TripleBuffer<MyOtherStruct>,
}

impl MyStruct {
    fn new() -> Self {
		buffer: TripleBuffer::new(&MyOtherStruct::default()),
	}
	
	fn update_buffer(&mut self) {
    	let new_entries = MyOtherStruct {
			...
		}
		
		let (mut buf_input, mut buf_output) = self.buffer.split();
		buf_input.write(sum);
		
		...
	}
}
```

In the above snippet the call to `split()` generates an error:

```
cannot move out of `self.buffer` which is behind a mutable reference
move occurs because `self.buffer` has type `TripleBuffer<MyOtherStruct>`, which does not implement the `Copy` trait rustcE0507
```

I have been reading about what other people have tried in that regard, but I cannot figure out what it is wrong. I though of trying to trick the compiler, but have not succeeded :) :

```rust
	fn update_buffer(&mut self) {
    	let new_entries = MyOtherStruct {
			...
		}
		
		let (mut buf_input, mut buf_output) = self.get_buffer();
		buf_input.write(sum);
		
		...
	}
	
	fn get_buffer(&self) -> (InputBufferType, OutputBufferType) {
		
		// read somewhere that by dereferencing and taking the reference I could overcome that
		//
		let selfish = &*self;
		selfish.buffer.split()
		
		// I have tried also the below, but still getting the error
		//
		//self.buffer.take().unwrap().split()
	}
	
}
```

The error I get now is pretty much on the same lines:

```
cannot move out of `selfish.buffer` which is behind a shared reference
move occurs because `selfish.buffer` has type `TripleBuffer<MyOtherStruct>`, which does not implement the `Copy` trait rustcE0507
```

I do understand what the error means but I cannot figure out a way to overcome that. I'm using the TripleBuffer as in the example just that I have it in a struct, so if that does not work, then how is it supposed to work I wonder. I have the producer and the consumer on different threads.  Can I take just the input buffer on the producer side and just the output buffer on the consumer side? Or do I always have to split them in tandem like the example.

I would appreciate any insight into the errors I'm seeing and how could I overcome that or some more complex example of using the TripleBuffer construct.

Thanks

**Comment by HadrienG2** [comment]
So, the API design goes like this: you build your triple buffer object, split it into a sender and receiver part, move one part in the sender thread and the other part in the receiver thread.

If I adjust the crate's introductory example a bit, you can do this:

```rust
// Create and split
let (mut buf_input, mut buf_output) = TripleBuffer::new(&0).split();

// Spawn sender thread which takes the buffer input (via move closure) and sends info
let handle = std::thread::spawn(move || buf_input.write(42));

// Fetch info from current (receiver) thread
let latest_value_ref = buf_output.read();
assert!(*latest_value_ref == 42 || *latest_value_ref == 0);
```

I thought about doing away with the split() API and [just returning an (Input, Output) pair from new()](https://github.com/HadrienG2/triple-buffer/issues/8), as std::sync::mpsc does, but...

- At the time, people had ideas about alternate storage designs that would use an unsplit buffer
- This crate has been around long enough that at this point, changing this feels like unnecessary churn

**Comment by celavek** [comment]
Thank you for the answer. I misunderstood the API. The example you provided it's much better in showing the semantics.
I had to realize that I do not need to keep around the initial TripleBuffer object, but its decompostition as you just showed.
I ended up with the following(based on my real code not the synthetic example from the original question):

```rust
type AggOutputBufferType = triple_buffer::Output<AggSummary>;
type AggInputBufferType = triple_buffer::Input<AggSummary>;

...

struct Aggregator {
	receiver: mpsc::Receiver<AggMessage>,
	input: Option<AggInputBufferType>,
	bids_streams: HashMap<String, Vec<AggBookEntry>>,
	asks_streams: HashMap<String, Vec<AggBookEntry>>,
}

...

fn get_buffer(&mut self) -> AggOutputBufferType {
		let buffer = TripleBuffer::new(&AggSummary::default());
		let (buf_input, buf_output) = buffer.split();
		self.input = Some(buf_input);
		buf_output
	}

```

**Comment by HadrienG2** [comment]
Thanks for your feedback! I just tagged v6.2.0 which adjusts the examples in the direction outlined above and also adds a shorthand for the `TripleBuffer::new().split()` pattern, hopefully this will make things easier for new users.
