### ISSUE TITLE
Optimize shared data layout to avoid false sharing

### ISSUE THREAD

**Issue by HadrienG2** [HadrienG2/triple-buffer#3]
The current implementation has minimal memory overhead, but can exhibit false sharing, which reduces the performance of concurrent reads and writes more than necessary. A more careful data layout could prevent this.

**Comment by HadrienG2** [comment]
So, what I want here is to align each buffer on a cache line boundary. The back-buffer index and the last buffer index can safely reside on the same cache line, because they are always accessed together.

Two tracks to explore, neither of which is currently available in stable or nightly Rust, are...

- Using repr(align) to manually align structs on a 64-bytes boundary, which is a typical cache line size. Tracking issue for the repr(align) RFC is https://github.com/rust-lang/rust/issues/33626.
- Using a facility dedicated to cache line alignment. This is being discussed as part of Rust issue https://github.com/rust-lang/rfcs/issues/1756.

**Comment by mkpankov** [comment]
> Using repr(align) to manually align structs on a 64-bytes boundary, which is a typical cache line size. Tracking issue for the repr(align) RFC is rust-lang/rust#33626.

It seems it's stable [now](https://github.com/rust-lang/rust/issues/33626#issuecomment-377500431).

**Comment by HadrienG2** [comment]
Indeed, and crossbeam-utils will introduce [a sane version of CachePadded](https://github.com/crossbeam-rs/crossbeam-utils/commit/2036321142641c47a2ba4c257690f74b6801cabb) in their next release. Once they release that, it will probably be the right time to update triple-buffer.

**Comment by HadrienG2** [comment]
Crossbeam have pushed new releases last month, so I can investigate this now.

**Comment by HadrienG2** [comment]
Fixed in v3
