### ISSUE TITLE
Make some tests require and force-enable the "raw" feature

### ISSUE THREAD

**Issue by HadrienG2** [HadrienG2/triple-buffer#6]
Cargo test's support for feature flags seems to be finicky. Tests which are marked as #[cfg(feature)] are not run, feature flags passed to cargo test are ignored when running doctests... It is not clear to which extent I can get it to work anyway, but right now it's not very satisfactory.

**Comment by HadrienG2** [comment]
Thankfully, this was partially caused by a misunderstanding from my part. The doctest is still broken, though...

**Comment by mkpankov** [comment]
I solved this in other project using separate binary crate in same workspace. It depends on the main library enabling the feature. Doesn't solve the doctests though.

**Comment by HadrienG2** [comment]
I don't know when exactly this was introduced, but current cargo allows you to enable features in doctests. This should allow a more elegant solution to the problem at hand.

**Comment by HadrienG2** [comment]
Ready for v3!
